# Generated by Django 5.2.7 on 2025-10-28 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("task", "executor")},
        ),
    ]
